### ISSUE TITLE
Response by trilateral expert group on species list (fish, mammals, birds)

### ISSUE THREAD

**Issue by obishelpdesk** [iobis/edna-species-lists#34]
On behalf of busch@waddensea-secretariat.org

Dear all,
here is the combined feedback of our trilateral expert groups.
Please let me know, in case you have questions. 

Fish

By fish group:

the presence of Allis shad (Alosa alosa), which is considered extinct from the rivers discharging into the Wadden Sea, may be either due to a confusion with Twaite shad or a plain sensation, since there have been dedicated monitoring programmes in the rivers, estuaries and coastal marine areas that must have found them if they were there.

Atherina boyeri	Big-scale sand smelt	occurrence in the WS questionable, no established species in the  North Sea according to the new German Red List of marine fishes (in prep.). 
 
Leuciscus leuciscus	Common dace	no established species in the North Sea according to the new German Red List of marine fishes (Freshwater List). BUT: Dutch data suggest that this species is able and willing to migrate towards and up to tidal locations such as Oostoever. It would be logical to assume they are present in the (fresh-brackish) tidal zones of larger rivers as well.

Micromesistius poutassou	Blue Whiting	occurrence in the WS questionable, bathypelagic; oceanodromous, depth range 150 - 3000 m

Boreogadus saida	Arctic cod, morue polaire - not in Wadden Sea species list

Chelidonichthys spinosus	 - not in Wadden Sea species list

Clupea pallasii	Pacific herring, hareng - not in Wadden Sea species list

Myoxocephalus quadricornis	fourhorn sculpin, chaboisseau à quatre cornes - not in Wadden Sea species list

Mugil cephalus	grey mullet, muge - not in Wadden Sea species list

Oncorhynchus clarkii	cutthroat trout, truite fardée- not in Wadden Sea species list

Phoxinus phoxinus	minnow, vairon- not in Wadden Sea species list

Salvelinus alpinus	Arctic charr, omble chevalier- not in Wadden Sea species list

Salvelinus fontinalis	brook trout, saumon de fontaine- not in Wadden Sea species list

Absence of fish species:
The absence of sea lamprey (Petromyzon marinus), for example, may be a seasonal phenomenon, 
 Likewise, fishing in the estuaries without catching ruffe (Gymnocephalus cernua) is rather unlikely, but the sampling spot at Neuwerk could be just beyond the species' salinity limit. 

General comments by Dutch colleague: 
- the Location Oostoever is a touristic location with fish restaurants. Additionally, it is a fishery harbor, this could lead to strange results.
-The results must viewed in the larger context, for example eDNA deterioration and origin of the water sampled.
-We have done eDNA sampling. There are still errors in the allocation of species names. Concretely, eDNA suggest presence of a species that has never been caught or seen at this location. 

Mammals
grey seals (Halichoerus grypus) should have been present in the samples
Myocastor coypus (mammal) - nutria is an invasive species, but we do not have it in our list of invasive species in the Wadden Sea. Traces from terrestrial system seem likely (like wild boar).

Birds
By bird groups:
•	Meleagris gallopavo                - could come from poultry and out with river water
•	Numenius madagascariensis – (Far-eastern Curlew) has never been recorded in Western Palearctic, so it must be an error. Since Curlew is on the list could it then be a Whimbrel Numenius phaeopus?
•	Passer domesticus                 – not a new species as presently indicated. A common passerine around buildings. Not a Wadden Sea species.
•	Spatula clypeata                     – not a new species as presently indicated. Maybe confusion because of new latin name.
•	Ardea cinerea                         – not a new species as presently indicated.
•	Anser cygnoides                     – not a new species as presently indicated.
•	Anas poecilorhyncha (Indian spot-billed duck) – must be a mistake, unless escaped from captivity

Molluscs
For the Molluscs there are two species that raise questions: Limapontia depressa, this is a shore snail, which is rather rare. The presence in a Wadden Sea study is possible, but it raise questions were has been sampled. Nucula nitidosa is a rare species as well, especially for the Wadden Sea area, further in the North Sea I would expect it, but still rarely.

General:
A recommendation we received is to compare the species found in the eDNA-samples with the full species list, and interprete species by species the probability of the record or, equally important, the lack thereof. 
--> we do not have the capacity to do this. But the suggestion to also look at the species that were not present, but would be expected is interesting. In the Wadden Sea case, this would hold true for the grey seal.

**Comment by SSuominen1** [comment]
Alosa alosa - not in list anymore after rerun with new database
Atherina boyeri - 100% matches to some of the ASVs. Also some of the ASVs have 100% matches to Atherina presbyterii. Change to genus to be sure?
Leuciscus leuciscus - 100% match, keep (there is a doubt that it could be there)
Micromesistius potassiu - 100% match, keep. An indication of a deep sea species, that we see in many of the sites. Therefore possible? 
Boreogadus saida - already removed
Chelidonichthys spinosus - change to genus
Clupea pallasii - not in the list anymore
Myoxocephalus quadricornis - change to local species M. scorpius
Mugil cephalus - 98% match, change to genus
Oncorhynchus clarkii - change to salmo trutta better match
Phoxinus phoxinus - same or better match to Alburnus alburnus, change
Salvelinus alpinus - 100% match to multiple species, not enough resolution, change to genus
Salvelinus fontinalis - 100% match and in the area, keep

**Comment by pieterprovoost** [comment]
Added annotations https://github.com/iobis/edna-results/commit/ee9966fb3d41a46d22a1dec61e11035a1e1b5704
