### ISSUE TITLE
Revision of the species list - UNESCO e-DNA

### ISSUE THREAD

**Issue by obishelpdesk** [iobis/edna-species-lists#37]
On behalf of ricardo.araujo@icmbio.gov.br

Dear colleagues,

We have seen that many species have been identified as species from other parts of the world that don't occur in Brazil, but this is probably due to the lack of genetic sequencing of the species here and the markers should not be so sensitive.
Many of these species are sister species to species that occur in the Caribbean, such as some corals, labridae fish, algae, sponges, among others.
On the other hand, many of our national species of ecological importance were not identified in the analysis, such as several species of sharks and rays, serranidae and epinephelidae fish, as well as invasive exotic species such as lionfish.

Yours sincerely,
Ricardo Araújo
ICMBio Fernando de Noronha

**Comment by pieterprovoost** [comment]
[Brazil_SpeciesList.xlsx](https://github.com/iobis/edna-species-lists/files/15332939/Brazil_SpeciesList.xlsx)

**Comment by SSuominen1** [comment]
annotations from excel file added
